export interface Country {
  id: string;
  text: string;
  flag: string;
}

const COUNTRY_ROWS = [
  ["ca_AD", "Andorra"],
  ["ar_AE", "United Arab Emirates"],
  ["en_AG", "Antigua & Barbuda"],
  ["sq_AL", "Albania"],
  ["es_AR", "Argentina"],
  ["de_AT", "Austria"],
  ["en_AU", "Australia"],
  ["bs_BA", "Bosnia & Herzegovina"],
  ["en_BB", "Barbados"],
  ["fr_BE", "Belgium"],
  ["bg_BG", "Bulgaria"],
  ["ar_BH", "Bahrain"],
  ["en_BM", "Bermuda"],
  ["es_BO", "Bolivia"],
  ["pt_BR", "Brazil"],
  ["en_BS", "Bahamas"],
  ["en_CA", "Canada"],
  ["de_CH", "Switzerland"],
  ["fr_CI", "Côte d’Ivoire"],
  ["es_CL", "Chile"],
  ["es_CO", "Colombia"],
  ["es_CR", "Costa Rica"],
  ["es_CU", "Cuba"],
  ["pt_CV", "Cape Verde"],
  ["cs_CZ", "Czechia"],
  ["de_DE", "Germany"],
  ["en_DK", "Denmark"],
  ["es_DO", "Dominican Republic"],
  ["ar_DZ", "Algeria"],
  ["es_EC", "Ecuador"],
  ["et_EE", "Estonia"],
  ["ar_EG", "Egypt"],
  ["es_ES", "Spain"],
  ["fi_FI", "Finland"],
  ["en_FJ", "Fiji"],
  ["fr_FR", "France"],
  ["fr_GF", "French Guiana"],
  ["en_GG", "Guernsey"],
  ["en_GH", "Ghana"],
  ["en_GI", "Gibraltar"],
  ["es_GQ", "Equatorial Guinea"],
  ["el_GR", "Greece"],
  ["es_GT", "Guatemala"],
  ["zh_HK", "Hong Kong SAR China"],
  ["es_HN", "Honduras"],
  ["hr_HR", "Croatia"],
  ["hu_HU", "Hungary"],
  ["en_ID", "Indonesia"],
  ["en_IE", "Ireland"],
  ["he_IL", "Israel"],
  ["en_IN", "India"],
  ["ar_IQ", "Iraq"],
  ["is_IS", "Iceland"],
  ["it_IT", "Italy"],
  ["en_JM", "Jamaica"],
  ["ar_JO", "Jordan"],
  ["ja_JP", "Japan"],
  ["en_KE", "Kenya"],
  ["ko_KR", "South Korea"],
  ["ar_KW", "Kuwait"],
  ["ar_LB", "Lebanon"],
  ["en_LC", "St. Lucia"],
  ["de_LI", "Liechtenstein"],
  ["lt_LT", "Lithuania"],
  ["lv_LV", "Latvia"],
  ["ar_LY", "Libya"],
  ["ar_MA", "Morocco"],
  ["fr_MC", "Monaco"],
  ["ro_MD", "Moldova"],
  ["mk_MK", "North Macedonia"],
  ["mt_MT", "Malta"],
  ["fr_MU", "Mauritius"],
  ["es_MX", "Mexico"],
  ["en_MY", "Malaysia"],
  ["pt_MZ", "Mozambique"],
  ["fr_NE", "Niger"],
  ["en_NG", "Nigeria"],
  ["en_NL", "Netherlands"],
  ["en_NO", "Norway"],
  ["en_NZ", "New Zealand"],
  ["ar_OM", "Oman"],
  ["es_PA", "Panama"],
  ["es_PE", "Peru"],
  ["fr_PF", "French Polynesia"],
  ["en_PH", "Philippines"],
  ["ur_PK", "Pakistan"],
  ["pl_PL", "Poland"],
  ["ar_PS", "Palestinian Territories"],
  ["pt_PT", "Portugal"],
  ["es_PY", "Paraguay"],
  ["ar_QA", "Qatar"],
  ["ro_RO", "Romania"],
  ["sr_RS", "Serbia"],
  ["ru_RU", "Russia"],
  ["ar_SA", "Saudi Arabia"],
  ["fr_SC", "Seychelles"],
  ["sv_SE", "Sweden"],
  ["en_SG", "Singapore"],
  ["sk_SK", "Slovakia"],
  ["sl_SI", "Slovenia"],
  ["it_SM", "San Marino"],
  ["fr_SN", "Senegal"],
  ["es_SV", "El Salvador"],
  ["en_TC", "Turks & Caicos Islands"],
  ["en_TH", "Thailand"],
  ["ar_TN", "Tunisia"],
  ["tr_TR", "Turkey"],
  ["en_TT", "Trinidad & Tobago"],
  ["zh_TW", "Taiwan"],
  ["en_UG", "Uganda"],
  ["en_GB", "United Kingdom"],
  ["en_US", "United States"],
  ["es_UY", "Uruguay"],
  ["it_VA", "Vatican City"],
  ["es_VE", "Venezuela"],
  ["sq_XK", "Kosovo"],
  ["ar_YE", "Yemen"],
  ["en_ZA", "South Africa"],
  ["en_ZM", "Zambia"],
] as const;

const REGIONAL_INDICATOR_OFFSET = 0x1f1a5;

function flagFromCountryCode(countryCode: string): string {
  const normalized = countryCode.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(normalized)) {
    return "🏳️";
  }

  return Array.from(normalized, (char) =>
    String.fromCodePoint(REGIONAL_INDICATOR_OFFSET + char.charCodeAt(0)),
  ).join("");
}

export const countries: Country[] = COUNTRY_ROWS.map(([id, text]) => {
  const [, countryCode = ""] = id.split("_");
  return {
    id,
    text,
    flag: flagFromCountryCode(countryCode),
  };
});
